.\""
.Dd May 22, 2007
.Dt FMR2FMR 1  
.Os Mac OS X       
.Sh NAME
.Nm fmr2fmr
.Nd Convert between Finger Minutiae Record formats.
.Sh SYNOPSIS
.Nm
.Fl i
.Ar infile
.Fl ti
.Ar intype
.Fl o
.Ar outfile
.Fl to
.Ar outtype
.Pp
.Sh DESCRIPTION
The
.Nm
command is used to convert files containing records of one finger minutiae
format to another. The record formats that are supported are ANSI/INCITS
378-2004 and the three ISO formats described in ISO/IEC 19794-2.
The conversion
is accomplished by modifying certain fields in the minutiae records based
on the representations used for the output file. For example, the
minutia angle is represented differently in the ISO and ANSI record formats.
In the ISO Compact Card format, some fields are further constrained, and
others are removed when compared to the full ISO format.
.Pp
Currently, the
.Nm
program ignores extended data blocks, and the output file will not have
any extended data.
.Pp
The options are as follows:
.Bl -tag -width "xxxxxxxxxxx"
.It Fl i\ \&infile
Specifies the file containing a complete Finger Minutiae Record;
.It Fl ti\ \&intype
Specifies the input file type;
.It Fl o\ \&outfile
Specifies the file that will contain the modified minutiae.
This file must not exist prior to execution of
.Nm ;
.It Fl to\ \&outtype
Specifies the output file type.
.El
.Pp
Valid types for the input and output files are:
.Bl -tag -width "xxxxxxxxxxx"
.It Cm ANSI
ANSI/INCITS 378-2004 format;
.It Cm ISO
ISO/IEC 19794-2 format;
.It Cm ISONC
ISO/IEC 19794-2 normal card format;
.It Cm ISOCC
ISO/IEC 19794-2 compact card format.
.El
.Sh EXAMPLES
.Nm
-i ansifmr.raw -ti ANSI -o isofmr.raw -to ISO
.Pp
Produces a new file containing the minutia record information from the
ANSI input file, converted to ISO format.
.Pp
.Sh SEE ALSO
.Xr mkfmr 1 ,
.Xr fmrplot 1 ,
.Xr fmrprune 1 ,
.Xr prfmr 1 .
.Sh STANDARDS
``Finger Minutiae Format for Data Interchange'', ANSI/INCITS 378-2004,
February 20, 2004.
.Pp
``Information Technology - Biometric data interchange formats - Part 2: 
Finger minutiae data'', ISO/IEC 19794-2, September 2005.
.Sh HISTORY
Created May 22nd, 2007 by NIST.
